4.4 OPENLDAP

diff --git a/ansible/roles/ibm-aiops-install-demo-content/tasks/25-post-ldap-register.yaml b/ansible/roles/ibm-aiops-install-demo-content/tasks/25-post-ldap-register.yaml
--- a/ansible/roles/ibm-aiops-install-demo-content/tasks/25-post-ldap-register.yaml
+++ b/ansible/roles/ibm-aiops-install-demo-content/tasks/25-post-ldap-register.yaml
@@ -82,53 +82,6 @@
 
 
 
-- name: 🚀 LDAPREGISTER - Get Cluster FQDN
-  shell: |
-    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
-    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
-    echo ${CLUSTER_FQDN##*console.}
-  register: CLUSTER_NAME
-
-
-- name: 🚀 LDAPREGISTER - Get CS Server
-  shell: |
-    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
-    echo "https://cp-console-$AIOPS_NAMESPACE.{{ CLUSTER_NAME.stdout_lines[0] }}"
-  register: CS_SERVER
-
-
-- name: 🚀 LDAPREGISTER - Get CS Server IP
-  shell:         
-    echo $(ping cp-console.{{ CLUSTER_NAME.stdout_lines[0] }} -c 1 -q | grep -m1 "("| awk '{print $3}' | sed "s/[(]//" | sed "s/[)]//" | sed "s/[:]//")
-  register: CS_SERVER_IP
-
-
-- name: 🚀 LDAPREGISTER - Get CS Server Password
-  shell: |
-    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
-    echo $(oc -n $AIOPS_NAMESPACE get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_password}' | base64 --decode)
-  register: CS_PWD
-
-    
-- name: 🚀 LDAPREGISTER - SC Login
-  shell:   
-    cloudctl login -a {{ CS_SERVER.stdout_lines[0] }} --skip-ssl-validation -u admin -p {{ CS_PWD.stdout_lines[0] }} -n kube-system
-  register: LOGIN
-- name: 🟣  OUTPUT
-  debug: 
-    var: LOGIN.stdout_lines
-    verbosity: 1
-
-
-- name: 🚀 LDAPREGISTER - Check already registered
-  shell:   
-    echo $(cloudctl iam resources|grep "Directory:LDAP")
-  register: LDAPS
-- name: 🟣  OUTPUT
-  debug: 
-    var: LDAPS.stdout_lines
-    verbosity: 2
-
 - name: Log
   shell: |
     export MESSAGE="   Register OpenLDAP Server"
@@ -155,49 +108,98 @@
   when: global_config.create_ocp_notifications | default(true) == true  
 
 
+
+
+
 - name: 🚀 LDAPREGISTER - Create LDAP Integration
-  block:
-  - name: 🚀 LDAPREGISTER -           📥 Register LDAP Server
-    shell:         
-      #echo 'cloudctl iam ldap-create "LDAP" --basedn "{{ LDAP_BASE }}" --server "ldap://openldap.default:389" --binddn "cn=admin,{{ LDAP_BASE }}" --binddn-password "{{ current_ldap_admin_password }}" -t "Custom" --group-filter "(&(cn=%v)(objectclass=groupOfUniqueNames))" --group-id-map "*:cn" --group-member-id-map "groupOfUniqueNames:uniqueMember" --user-filter "(&(uid=%v)(objectclass=Person))" --user-id-map "*:uid"'
-      cloudctl iam ldap-create "LDAP" --basedn {{ current_ibmaiops_feature.ldap_base }} --server ldap://openldap.{{ current_ibmaiops_feature.ldap_namespace }}:389 --binddn cn=admin,{{ current_ibmaiops_feature.ldap_base }} --binddn-password {{ current_ldap_admin_password }} -t "Custom" --group-filter "(&(cn=%v)(objectclass=groupOfUniqueNames))" --group-id-map "*:cn" --group-member-id-map "groupOfUniqueNames:uniqueMember" --user-filter "(&(uid=%v)(objectclass=Person))" --user-id-map "*:uid"
-    ignore_errors: true
-    register: LOGIN
-  - name: 🟣  OUTPUT
-    debug: 
-      var: LOGIN.stdout_lines
-      verbosity: 1
+  shell: |
+    set -x
+    
+    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
+    echo "       🛠️   Get Route"
+    export ROUTE=$(oc get route -n $AIOPS_NAMESPACE cpd  -o jsonpath={.spec.host})          
+    echo "        Route: $ROUTE"
+    echo ""
+ 
+    echo "       🛠️   Getting ZEN Token"
+  
+    ZEN_API_HOST=$(oc get route -n $AIOPS_NAMESPACE cpd -o jsonpath='{.spec.host}')
+    ZEN_LOGIN_URL="https://${ZEN_API_HOST}/v1/preauth/signin"
+    LOGIN_USER=admin
+    LOGIN_PASSWORD="$(oc get secret admin-user-details -n $AIOPS_NAMESPACE -o jsonpath='{ .data.initial_admin_password }' | base64 --decode)"
 
-  # - name: LDAPREGISTER -           📥 Get Team ID
-  #   shell:         
-  #     echo $(cloudctl iam teams | awk '{print $1}'| sed -n 2p)
-  #   register: TEAM_ID
+    ZEN_LOGIN_RESPONSE=$(
+    curl -k \
+    -H 'Content-Type: application/json' \
+    -XPOST \
+    "${ZEN_LOGIN_URL}" \
+    -d '{
+          "username": "'"${LOGIN_USER}"'",
+          "password": "'"${LOGIN_PASSWORD}"'"
+    }' 2> /dev/null
+    )
+
+    ZEN_LOGIN_MESSAGE=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .message)
+
+    if [ "${ZEN_LOGIN_MESSAGE}" != "success" ]; then
+    echo "Login failed: ${ZEN_LOGIN_MESSAGE}" 1>&2
+
+    exit 2
+    fi
+
+    ZEN_TOKEN=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .token)
+    echo "${ZEN_TOKEN}"
+
+    echo "Sucessfully logged in" 1>&2
+
+    echo ""
 
 
-  # - name: LDAPREGISTER -           📥 Register Users and Teams
-  #   shell: |
-  #     cloudctl iam user-import -u demo -f
-  #     cloudctl iam user-import -u dev -f
-  #     cloudctl iam user-import -u test -f
-  #     cloudctl iam user-import -u prod -f
-  #     cloudctl iam user-import -u boss -f
-  #     cloudctl iam user-import -u nik -f
-  #     cloudctl iam user-import -u sre1 -f
-  #     cloudctl iam user-import -u sre2 -f
+    echo "***************************************************************************************************************************************************"
+    echo "   🛠️   Create LDAP Integration"
+    export result=$(curl -i -k -X POST https://cp-console-ibm-aiops.apps.65ad080ec81d780010b37cf4.cloud.techzone.ibm.com:443/idprovider/v3/auth/idsource/ \
+    --header "Authorization: Bearer $ACCESS_TOKEN" \
+    --header "Content-Type: application/json" \
+    -d '{
+            "name": "LDAP",
+            "description": "",
+            "protocol": "ldap",
+            "type": "Custom",
+            "idp_config": {
+                "ldap_id": "LDAP",
+                "ldap_realm": "REALM",
+                "ldap_url": "ldap://openldap.openldap:389",
+                "ldap_host": "openldap.openldap",
+                "ldap_port": "389",
+                "ldap_protocol": "ldap",
+                "ldap_basedn": "dc=ibm,dc=com",
+                "ldap_binddn": "cn=admin,dc=ibm,dc=com",
+                "ldap_bindpassword": "UDRzc3cwcmQh",
+                "ldap_type": "Custom",
+                "ldap_ignorecase": "false",
+                "ldap_userfilter": "(&(uid=%v)(objectclass=Person))",
+                "ldap_useridmap": "*:uid",
+                "ldap_groupfilter": "(&(cn=%v)(objectclass=groupOfUniqueNames))",
+                "ldap_groupidmap": "*:cn",
+                "ldap_groupmemberidmap": "groupOfUniqueNames:uniqueMember",
+                "ldap_nestedsearch": "false",
+                "ldap_pagingsearch": "false"
+            }
+        }')
+    echo "      🔎 Result: "
+    echo "       "$result | sed 's/^/          /'
 
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} ClusterAdministrator -u demo
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} Administrator -u dev
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} Administrator -u test
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} Administrator -u prod
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} ClusterAdministrator -u boss    
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} ClusterAdministrator -u nik
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} ClusterAdministrator -u sre1
-  #     cloudctl iam team-add-users {{ TEAM_ID.stdout_lines[0] }} ClusterAdministrator -u sre2
 
-  #     cloudctl iam resource-add {{ TEAM_ID.stdout_lines[0] }} -r crn:v1:icp:private:iam::::Directory:LDAP
-  #   register: TEAMS
-  #   ignore_errors: true
-  when: LDAPS.stdout_lines|length == 0
+    sleep 30
+  ignore_errors: true
+  register: REGLDAP
+
+
+- name: 🟣  OUTPUT
+  debug: 
+    var: REGLDAP.stdout_lines
+    verbosity: 1
+
 
 
 
@@ -226,6 +228,8 @@
   args:
     executable: /bin/bash
   when: global_config.create_ocp_notifications | default(true) == true  
+
+
 
 
 
@@ -271,148 +275,6 @@
     echo "Sucessfully logged in" 1>&2
 
     echo ""
-
-    echo "***************************************************************************************************************************************************"
-    echo "   🛠️   Create Demo Admin Role"
-    echo "     "	
-    export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v1/role" \
-      -H "Authorization: bearer $ZEN_TOKEN" \
-      -H 'Content-Type: application/json; charset=utf-8' \
-      -d '{
-            "role_name": "Demo Admin",
-          "description": "Demo Admin",
-          "permissions": [
-            "administrator",
-            "can_provision",
-            "secure_tunnel_network",
-            "secure_tunnel_port_forwarding",
-            "secure_tunnel_connector_install",
-            "secure_tunnel_create_template",
-            "secure_tunnel_renew_cert",
-            "secure_tunnel_view_audit_log",
-            "aiops_manage_integrations",
-            "aiops_view_integrations",
-            "aiops_view_topologies",
-            "aiops_manage_topology_templates",
-            "aiops_manage_topology_comments",
-            "aiops_manage_applications",
-            "aiops_manage_business_context",
-            "aiops_manage_topology_tools",
-            "aiops_manage_topology_presentation",
-            "aiops_manage_topology_rules",
-            "aiops_manage_advanced_topology_settings",
-            "aiops_view_aimodels_status",
-            "aiops_manage_aimodels",
-            "aiops_view_operational_policies",
-            "aiops_manage_runbooks",
-            "aiops_use_runbooks",
-            "aiops_author_runbooks",
-            "aiops_administer_runbooks",
-            "aiops_view_operational_data",
-            "aiops_edit_operational_policies",
-            "aiops_delete_operational_policies",
-            "aiops_use_insights_dashboard"
-          ]
-    }')
-    echo "      🔎 Result: "
-    echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
-    export demo_admin_id=$(echo $result|jq -r ".id")
-    echo "       Demo Admin Role ID: $demo_admin_id" | sed 's/^/          /'
-
-
-
-    echo "***************************************************************************************************************************************************"
-    echo "   🛠️   Create Demo_Viewer Role"
-    echo "     "	
-    export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v1/role" \
-      -H "Authorization: bearer $ZEN_TOKEN" \
-      -H 'Content-Type: application/json; charset=utf-8' \
-      -d '{
-            "role_name": "Demo Viewer",
-          "description": "Demo Viewer",
-            "permissions": [
-              "aiops_view_aimodels_status",
-              "aiops_view_topologies",
-              "aiops_view_operational_data",
-              "aiops_use_insights_dashboard",
-              "aiops_view_integrations",
-              "aiops_view_operational_policies",
-              "view_platform_health",
-              "aiops_manage_topology_comments",
-              "aiops_manage_applications",
-              "aiops_use_runbooks"
-            ]
-    }')
-    echo "      🔎 Result: "
-    echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
-    export demo_viewer_id=$(echo $result|jq -r ".id")
-    echo "       Demo Viewer Role ID: $demo_viewer_id" | sed 's/^/          /'
-
-
-
-    # echo "***************************************************************************************************************************************************"
-    # echo "   🛠️   Create Demo Admin Group"
-    # echo "     "	
-    # export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v2/groups" \
-    #   -H "Authorization: bearer $ZEN_TOKEN" \
-    #   -H 'Content-Type: application/json; charset=utf-8' \
-    #   -d '{
-    #   "account_id": 1000,
-    #         "name": "Demo Admin Group",
-    #   "description": "Demo Admin Group",
-    #   "role_identifiers": [
-    #     "'$demo_admin_id'"
-    #   ]
-    # }')
-    # echo "      🔎 Result: "
-    # echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
-    # echo "     "	
-    # echo "     "	
-
-    # echo "***************************************************************************************************************************************************"
-    # echo "   🛠️   Create Demo Viewer Group"
-    # echo "     "	
-    # export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v2/groups" \
-    #   -H "Authorization: bearer $ZEN_TOKEN" \
-    #   -H 'Content-Type: application/json; charset=utf-8' \
-    #   -d '{
-    #   "account_id": 1000,
-    #         "name": "Demo Viewer Group",
-    #   "description": "Demo Viewer Group",
-    #   "role_identifiers": [
-    #     "'$demo_viewer_id'"
-    #   ]
-    # }')
-    # echo "      🔎 Result: "
-    # echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
-    # echo "     "	
-    # echo "     "	
-
-
-
-
-    # echo "***************************************************************************************************************************************************"
-    # echo "   🛠️   Create Demo Viewer Member"
-    # echo "     "	
-    # export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v2/groups/10002/members" \
-    #   -H "Authorization: bearer $ZEN_TOKEN" \
-    #   -H 'Content-Type: application/json; charset=utf-8' \
-    #   -d '{
-    #       "ldap_groups": [
-    #         "demo"
-    #       ],
-    #       "user_identifiers": [
-    #         0
-    #       ]
-    #     }')
-    # echo "      🔎 Result: "
-    # echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
-    # echo "     "	
-    # echo "     "	
-
-
-
-
 
 
 
