Probable Cause - Topology Hack for 4.3

diff --git a/ansible/roles/ibm-aiops-install-demo-content/tasks/43_ibm-aiops-create-topology.yaml b/ansible/roles/ibm-aiops-install-demo-content/tasks/43_ibm-aiops-create-topology.yaml
--- a/ansible/roles/ibm-aiops-install-demo-content/tasks/43_ibm-aiops-create-topology.yaml
+++ b/ansible/roles/ibm-aiops-install-demo-content/tasks/43_ibm-aiops-create-topology.yaml
@@ -991,3 +991,89 @@
 
 
 
+# --------------------------------------------------------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------------------------------------------------------
+# Probable Cause Hack for 4.3 
+# --------------------------------------------------------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------------------------------------------------------
+- name: 🚀 TOPOLOGY - Probable Cause Hack for 4.3  
+  shell: |
+    set -x
+    
+    # 61654
+    echo "***************************************************************************************************************************************************"
+    echo "***************************************************************************************************************************************************"
+    echo "                                                                                                                                                   "
+    echo " 🚀 Topology Probable Cause Hack for 4.3                                                                                                                                              "
+    echo "                                                                                                                                                   "
+    echo "***************************************************************************************************************************************************"
+
+
+    echo "🌏 GET ZEN TOKEN"
+
+    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
+    echo "       🛠️   Get Route"
+    export ROUTE=$(oc get route -n $AIOPS_NAMESPACE cpd  -o jsonpath={.spec.host})          
+    echo "        Route: $ROUTE"
+    echo ""
+
+    echo "       🛠️   Getting ZEN Token"
+  
+    ZEN_API_HOST=$(oc get route -n $AIOPS_NAMESPACE cpd -o jsonpath='{.spec.host}')
+    ZEN_LOGIN_URL="https://${ZEN_API_HOST}/v1/preauth/signin"
+    LOGIN_USER=admin
+    LOGIN_PASSWORD="$(oc get secret admin-user-details -n $AIOPS_NAMESPACE -o jsonpath='{ .data.initial_admin_password }' | base64 --decode)"
+
+    ZEN_LOGIN_RESPONSE=$(
+    curl -k \
+    -H 'Content-Type: application/json' \
+    -XPOST \
+    "${ZEN_LOGIN_URL}" \
+    -d '{
+          "username": "'"${LOGIN_USER}"'",
+          "password": "'"${LOGIN_PASSWORD}"'"
+    }' 2> /dev/null
+    )
+
+    ZEN_LOGIN_MESSAGE=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .message)
+
+    if [ "${ZEN_LOGIN_MESSAGE}" != "success" ]; then
+    echo "Login failed: ${ZEN_LOGIN_MESSAGE}" 1>&2
+
+    exit 2
+    fi
+
+    ZEN_TOKEN=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .token)
+    echo "${ZEN_TOKEN}"
+
+    echo "Sucessfully logged in" 1>&2
+
+    echo "🚀 Patch Topology Probable Cause"
+
+    curl -s -k -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" -d '{"edge_type_list":[{ "edge": "accesses", "label": "association", "outdegree": 20,"indegree": 5}]}'
+    curl -s -k -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" -d '{"edge_type_list":[{ "edge": "calls", "label": "association", "outdegree": 20,"indegree": 5}]}'
+    curl -s -k -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" -d '{"edge_type_list":[{ "edge": "exposedBy", "label": "association", "outdegree": 20,"indegree": 5}]}'
+    curl -s -k -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" -d '{"edge_type_list":[{ "edge": "runsOn", "label": "association", "outdegree": 20,"indegree": 5}]}'
+
+
+    curl  -k -X GET -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" | jq | grep accesses
+    curl  -k -X GET -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" | jq | grep calls
+    curl  -k -X GET -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" | jq | grep exposedBy
+    curl  -k -X GET -H "Content-Type: application/json" -H "Authorization: Bearer ${ZEN_TOKEN}" https://$ROUTE/aiops/api/issue-resolution/mime/v1/customisation/edge_type -H "X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255" | jq | grep runsOn
+
+    oc scale deploy aiops-ir-analytics-probablecause --replicas=0
+    oc scale deploy aiops-ir-analytics-probablecause --replicas=1
+
+
+  register: output_string
+  ignore_errors: true
+  args:
+    executable: /bin/bash
+
+- name: 🟣  OUTPUT
+  debug: 
+    var: output_string.stdout_lines
+    verbosity: 1
+  #when: PRINT_LOGINS == true
+
+
